FROM ubuntu:latest
WORKDIR /porter
RUN apt update
RUN apt -y install curl
RUN curl -fsSL https://get.docker.com -o get-docker.sh
RUN chmod u+x get-docker.sh
RUN ./get-docker.sh
RUN curl -L https://cdn.porter.sh/latest/install-linux.sh | bash
RUN export PATH="$PATH:~/.porter"
ENV PATH="$PATH:~/.porter" 
