FROM gradle:jdk11
EXPOSE 9000/tcp
COPY --chown=gradle:gradle . /prior-auth/
RUN keytool -import -alias mitre_ba_root -file "/prior-auth/MITRE BA Root.crt" \
    -keystore "$JAVA_HOME/lib/security/cacerts" -storepass changeit -noprompt -trustcacerts
RUN keytool -import -alias mitre_ba_npe_ca3 -file "/prior-auth/MITRE BA NPE CA-3.crt" \
    -keystore "$JAVA_HOME/lib/security/cacerts" -storepass changeit -noprompt -trustcacerts
WORKDIR /prior-auth/
RUN gradle installBootDist
CMD ["gradle", "bootRun", "--args='debug'"]