name: Porter Windows Docker Image CD

on:
  push:
    branches: [ dev ]
  workflow_dispatch:

jobs:
  docker-cd: 
    runs-on: ubuntu-latest
    steps:

    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}
      
    - name: Build and push Porter Windows Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: Dockerfile.porter-windows
        push: true
        tags: smalho01234/fullstack_drls_pas-windows:current
