name: Porter Windows Docker Image CI

on:
  pull_request:
    branches: [ master, dev ]
  workflow_dispatch:


jobs:
  docker-ci: 
    runs-on: ubuntu-latest
    steps:

    - name: Checkout Repository
      uses: actions/checkout@v2
      
    - name: Test Porter Windows Docker image Builds
      run: docker build -f Dockerfile.porter-windows .